#!/usr/bin/env bash
#using the while loop again
i=0
while [ $i -le 19 ];
do
i=$(( i+1 ))
    case $i in
        4) echo "4"
           echo "bad luck from China"
           ;;
        9) echo "9"
           echo "bad luck from Japan"
           ;;
        17) echo "17"
            echo "bad luck from Italy"
            ;;
        $i) echo $i
        ;;
    esac
    done
