#!/usr/bin/env bash
#more of the last loop
count=1

while [ $count -le 20 ]; do
    if [ $count -eq 4 ]; then
        echo "$count and then bad luck from China"
    elif [ $count -eq 9 ]; then
        echo "$count and then bad luck from Japan"
    elif [ $count -eq 17 ]; then
        echo "$count and then bad luck from Italy"
    else
        echo $count
    fi
    ((count++))
done

