#!/usr/bin/env bash
#Display information about the "school" file, which include if this file ex\
ists, empty, or regular.
fname="school"
if [ -e "$fname" ]
then
        echo "school file exists"
        if [ -s "$fname" ]
        then
                echo "school file is not empty"
        else
                echo "school file is empty"
        fi
        if [ -f "$fname" ]
        then
                echo "school is a regular file"
        fi
else
        echo "school file does not exist"
fi
